---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app

namespace: "cartography"
namePrefix: "cartography-"
images:
  - name: "mattcl/st-cartography"
    newTag: "202549041049"


configMapGenerator:
  - name: app-config
    envs:
      - "app-config.env"

